version: '3.8'

services:
  redis:
    image: redis:alpine
    command:
      - redis-server
    env_file:
      - .env
    restart: on-failure
    ports:
      - "6378:6379"
  tg_db:
    image: postgres:14-alpine
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    restart: on-failure
    ports:
      - "5433:5432"
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "python -m bot"
    env_file:
      - .env
    restart: always
    depends_on:
      - tg_db
      - redis

volumes:
  pgdata:
